import Navbar from "@/components/Navbar";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./themeprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <UserProvider>
                <body className={inter.className}>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="dark"
                        enableSystem
                    >
                        <main className="dark:bg-slate-800">
                            <Navbar />
                            {children}
                        </main>
                    </ThemeProvider>
                </body>
            </UserProvider>
        </html>
    );
}
