import Navbar from "@/components/Navbar";
import Provider from "@/components/Provider";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./themeprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Disc Golf Team Challenge",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${inter.className} scroll-smooth antialiased`}>
                <Provider>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="dark"
                        enableSystem
                    >
                        <main className="w-screen h-screen">
                            <Navbar />
                            {children}
                        </main>
                    </ThemeProvider>
                </Provider>
            </body>
        </html>
    );
}
